name: Update README
on: workflow_dispatch

permissions:
  contents: write
  pull-requests: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Update README file
      run: |
       tmpfile=$(mktemp)
       latest13=$(curl -sL https://api.github.com/repos/rancher/rke/tags?per_page=1000 | jq -r 'first(.[] | select(.name | startswith("v1.3")) | select(.name | contains("rc") | not) | .name)')
       latest12=$(curl -sL https://api.github.com/repos/rancher/rke/tags?per_page=1000 | jq -r 'first(.[] | select(.name | startswith("v1.2")) | select(.name | contains("rc") | not) | .name)')
       echo "* v1.3" > $tmpfile
       echo "  * ${latest13} - Read the full release [notes](https://github.com/rancher/rke/releases/tag/${latest13})." >> $tmpfile
       echo "* v1.2" >> $tmpfile
       echo "  * ${latest12} - Read the full release [notes](https://github.com/rancher/rke/releases/tag/${latest12})." >> $tmpfile
       sed -e '/## Latest Release/r '"$tmpfile"'' -e 's/CURRENTYEAR/'"$(date +%Y)"'/g' README-template.md > README.md
    - name: Check for repository changes
      run: |
        if git diff --name-only --exit-code; then
          echo "No changes found in repository after updating README"
          echo "changes_exist=false" >> $GITHUB_ENV
        else
          echo "Changes found in repository after updating README:"
          git diff --name-only
          echo "changes_exist=true" >> $GITHUB_ENV
        fi
    - name: Create branch, commit and push
      if: ${{ env.changes_exist == 'true' }}
      id: branch
      run: |
        BRANCH="githubaction-update-readme-$(date +%Y-%m-%d-%H-%M-%S)"
        echo "::set-output name=branch::$BRANCH"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git checkout -b "$BRANCH"
        git commit -a -m "update README with latest"
        git push origin "$BRANCH"
    - name: Create Pull Request
      if: ${{ env.changes_exist == 'true' }}
      id: cpr
      env:
        SOURCE_BRANCH: ${{ steps.branch.outputs.branch }}
      uses: actions/github-script@v5.0.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          let body = 'Auto-generated by GitHub Actions'

          const { data: pr } = await github.rest.pulls.create({
            title: `[${{ github.ref_name }}] update README with latest`,
            body: body,
            owner: context.repo.owner,
            repo: context.repo.repo,
            base: "${{ github.ref_name }}",
            head: `${ process.env.SOURCE_BRANCH }`
          });
          await github.rest.issues.addLabels({
            ...context.repo,
            issue_number: pr.number,
            labels: ["status/auto-created"],
          });
          console.log('Created new pull request');
          return pr.html_url;
    - name: Check outputs
      if: ${{ env.changes_exist == 'true' }}
      run: |
        echo "Pull Request URL - ${{ steps.cpr.outputs.result }}"
